### ISSUE TITLE
could it port to afl ?

### ISSUE THREAD

**Issue by ricardo-kcc** [adrianherrera/ball-larus-fuzz#1]
it's cool! could it suitable for afl?

**Comment by adrianherrera** [comment]
This repo combines it with AFL++.

**Comment by vanhauser-thc** [comment]
I think he means that there is no doc that explains how to use it with afl++. for someone not used to llvm plugins that is a big unknown.

**Comment by ricardo-kcc** [comment]
yeah，I want to know how to use it and what changed afl /afl++ should when compiled program by using it.

**Comment by adrianherrera** [comment]
Sure, makes sense. Given I've just pushed this and am still tinkering with the implementation myself, I have not written any docs yet. I will once I convince myself that it actually works and is useful :)
